export const baseContentFields = {
  id: null,
  slug: "",
  title: "",
  description: "",
  contentType: "",
  status: "draft",
  featured: false,
  authorId: null,
  tags: [],
  categories: [],
  technologies: [],
  githubUrl: "",
  websiteUrl: "",
  documentationUrl: "",
  version: "",
  createdAt: null,
  updatedAt: null,
  publishedAt: null,
  seo: {
    title: "",
    description: "",
    canonical: "",
    ogTitle: "",
    ogDescription: "",
    ogImage: "",
  },
};